version: "3.7"

services:
  backend:
    environment:
      NODE_ENV: "docker"
    build:
      context: ./backend
      dockerfile: dockerfile.local
    image: ai-alert/backend
    volumes:
      - ./backend:/package/backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file: backend/.env

  postgres:
    container_name: postgres
    image: postgres:14.0-alpine
    environment:
      TZ: GMT
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    env_file: backend/.env

volumes:
  pgdata:
