FROM node:12.22.9

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install

ENV NODE_ENV="local"

# Bundle app source
COPY . .

# Expose server port
EXPOSE 5000

# Start the app
CMD [ "npm", "run", "start" ]